import { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
	title: {
		absolute: '',
		default: 'My First Next App',
		template: '%s | Xcode',
	},
	description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body>
				<div style={{ backgroundColor: 'lightcyan', padding: '20px' }}>
					<h2 style={{ textAlign: 'center' }} className='text-red-700'>
						Header
					</h2>
				</div>
				{children}
				<div style={{ backgroundColor: 'lightcyan', padding: '20px', marginTop: '50px' }}>
					<h2 style={{ textAlign: 'center' }}>Footer</h2>
				</div>
			</body>
		</html>
	);
}
